name: Generate User Repos ZIP

on:
  release:
    types: [published]

jobs:
  generate-zip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pygithub
        
    - name: Extract username from release name
      id: extract-user
      run: |
        RELEASE_NAME="${{ github.event.release.name }}"
        if [[ $RELEASE_NAME == repos-* ]]; then
          USERNAME=${RELEASE_NAME#repos-}
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "Extracted username: $USERNAME"
        else
          echo "Release name doesn't match pattern: $RELEASE_NAME"
          exit 1
        fi
        
    - name: Download and create ZIP
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/scripts/download_repos.py "$USERNAME"
        
    - name: Upload ZIP to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./$USERNAME-repositories.zip
        asset_name: $USERNAME-repositories.zip
        asset_content_type: application/zip
